### ISSUE TITLE
use id returned via /streamids or /streams within seedlink

### ISSUE THREAD

**Issue by crotwell** [EarthScope/ringserver#12]
Output of /streamids looks like `AK_BCP__BHE` and /streams looks like `AK_BCP__BHE/MSEED` but to feed that back into seedlink to get a realtime feed the client has to change it to
```
STATION BCP AK
SELECT --BHE.D
```
which is not intuitive. Would be much nicer if a client could use one of `AK_BCP__BHE` or `AK_BCP__BHE/MSEED` withing the seedlink select, maybe like:
```
SELECT AK_BCP__BHE/MSEED
```

Basically would be nice if ringserver would eat its own dogfood! :)

I realize this extends the seedlink protocol, which may be a problem.

**Comment by chad-iris** [comment]
Ringserver eats it's own dog food via DataLink, which is the native protocol so to speak.  There could be another endpoint for producing SeedLink-style input, but honestly I'm not sure it's worth it.  I'll leave this here as an idea.

**Comment by chad-earthscope** [comment]
The SeedLink protocol [has now been standardized](https://docs.fdsn.org/projects/seedlink/en/latest/), but the selection IDs are still split between NET_STA and LOC_CHAN.  This is not an extension worth doing with just ringserver.
