### ISSUE TITLE
rx and tx log filenames include colon

### ISSUE THREAD

**Issue by crotwell** [EarthScope/ringserver#31]
Filenames for the tx and rx log files look like:
`rxlog-20211005T00:00-20211006T00:00`

Would be nicer for the shell if there wasn't a colon between the hour and minute.  Especially since the date part is using ISO short form, eg there isn't a dash between year, month  and day.

**Comment by chad-iris** [comment]
Agreed, fewer weird characters and consistency would be better.  It would also become Windows compliant for what that's worth.  I don't want to change it until a major release, as I'm sure folks have written stuff around the current naming.
