### ISSUE TITLE
datetimes to use 'T' separator for strict ISO8601 conformance

### ISSUE THREAD

**Issue by crotwell** [EarthScope/ringserver#32]
Dates in INFO STATUS, etc, look like `2021-10-25 14:02:04.060115` which is almost but not quite ISO format. Would be nice to standardize all dates to use iso8601, replace the space with a 'T'.

Also, include Z on dates so timezone is not ambiguous.

**Comment by chad-earthscope** [comment]
done in version 4.0.0
