### ISSUE TITLE
std types for datalink

### ISSUE THREAD

**Issue by crotwell** [EarthScope/ringserver#40]
Note sure if this should be in ringserver or libdali, but would be nice if there was a convention on types in datalink stream ids.

Currently `/MSEED` is common for miniseed2. Perhaps also define:
`/MSEED3` for miniseed3
`/JSON` for JSON
`/BZJSON` for bzip2 compressed JSON

Not sure there would ever be a use case for this, but perhaps also QuakeML and StationXML types?

**Comment by chad-earthscope** [comment]
My intention is to use:

* `/MSEED` for miniSEED of undefined version
* `/MSEED2` for miniSEED v2
* `/MSEED3` for miniSEED v3

If anywhere it should go into the DataLink documentation included with libdali.  These will always be guidelines in my mind and not requirements or limits to what can be used.
