### ISSUE TITLE
TLS Support?

### ISSUE THREAD

**Issue by tparker-usgs** [EarthScope/ringserver#44]
The push to encrypt all network traffic is making it increasingly difficult to operate unencrypted services. Adding TLS support would be very welcome.

**Comment by chad-earthscope** [comment]
TLS is on the horizon, likely part of an update to support SeedLink v4 (spec is currently in review) or shortly thereafter.  The v4 protocol includes authorization, which must be done in TLS.

**Comment by chad-earthscope** [comment]
Relatedly, the SeedLink client library has support for TLS now: https://github.com/EarthScope/libslink

As for ringserver, one option, perhaps even preferable for some, would be to use something like haproxy or stunnel in front of ringserver to handle the TLS termination.  On most linux distros installing and configuring haproxy is near trivial.
