### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by Darcula666** [EarthScope/ringserver#48]
[MSeedScan] Cannot open directory /home/redare/server/ringserver/data/miniseed: Too many open files

**Comment by chad-earthscope** [comment]
Hi @Darcula666 
Do you have any more details?  How many files are in the directory being scanned? 

You may wish to use the `ulimit` command to allow your ringserver process to open more files at once.

**Comment by chad-earthscope** [comment]
Closing this issue.  In general it is solved by changing the number of allowed open files per-processes with `ulimit`.
