### ISSUE TITLE
Ringserver uses all of the available CPU time

### ISSUE THREAD

**Issue by bkuschak** [EarthScope/ringserver#54]
I'm often seeing this fault where ringserver gets stuck using all of the available CPU time.  It seems to occur when ringserver is started and a client queries the ringserver for data, before it contains any data.  Any suggestions?
                                              
- ringserver gets stuck at nearly ~100% cpu time, and remains in this state forever.
- A program is conencted as a Datalink client, but it is not providing any data at this time.
- The ringserver has just been started (-VOLATILE) and it contains no data at this time.
- An obspy SeedlinkClient has connected to the ringserver to request recent 24 hours of data.
- In the past I've seen this same failure when it was Swarm requesting data instead of obspy.
 
See the attached file for details.
[debugging_ringserver.txt](https://github.com/user-attachments/files/16534580/debugging_ringserver.txt)

**Comment by chad-earthscope** [comment]
Thanks for the report @bkuschak 

I've see a high CPU symptom before but had not been able to repeat it.  With your information I can now repeat it.  An empty ring, with a single SeedLink client request for a time window of data triggers a spiral use of CPU.

**Comment by chad-earthscope** [comment]
I belive this is fixed in v4.0.0.
If not please reopen this issue (or create a new one).

**Comment by bkuschak** [comment]
Thanks for implementing a fix.  I'll give v4.0.0 a try within the next few weeks and report back.
