### ISSUE TITLE
datalink 1.1 generate seq numbers

### ISSUE THREAD

**Issue by crotwell** [EarthScope/ringserver#62]
> With the DataLink v1.1 protocol a client may submit packets with a specified packet ID to use instead of a generated ID.

How does one do this? Is there documentation for datalink 1.1?

**Comment by chad-earthscope** [comment]
>> With the DataLink v1.1 protocol a client may submit packets with a specified packet ID to use instead of a generated ID.

>How does one do this? Is there documentation for datalink 1.1?

In the protocol doc here (rendering currently broken, so you have to read doxygen syntax for now):
https://github.com/EarthScope/libdali/blob/1f9d95a01c18da4bdce950dc793d2f621aa80b05/doc/DataLink.protocol.dox#L96

I'm not done with DataLink 1.1, so it's not a "declared" release yet; it will also include an `AUTH` command and a TLS port.  Also, a Change section to identify what has changed between versions.
