### ISSUE TITLE
Initialize stream count value 

### ISSUE THREAD

**Issue by chad-earthscope** [EarthScope/ringserver#9]
http://localhost:18000/connections

> localhost [127.0.0.1:62397]
  [Unknown] Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0  2018-02-14 07:20:52.542232
  Packet 0 (1902-01-01 00:00:00.000000)  Lag -, 0.1
  TX 0 packets, 0.0 packets/sec  0 bytes, 0.0 bytes/sec
  RX 0 packets, 0.0 packets/sec  0 bytes, 0.0 bytes/sec
  Stream count: -209036841
  Match: -
  Reject: -

The `Stream count: -209036841` is likely due to an uninitialized value on client connect.

**Comment by chad-iris** [comment]
On inspection the value is initialized.  For now, I cannot reproduce this.
